---
- name: Install and start Nginx
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: refresh cache if older than 1 hour

    - name: Install Nginx
      apt:
        name: nginx
        state: latest

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes


